### ISSUE TITLE
Insights roadmap

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltPlot#38]
This issue describes the roadmap for tools that provide insights. The items flagged with FIXME don'e belong to tiltData and will be moved elsewhere. 

## References

* Private [slack message](https://2investinginitiative.slack.com/archives/D01JA76GDTR/p1693915494739589?thread_ts=1693915473.726389&cid=D01JA76GDTR)
* Private [googledoc](https://docs.google.com/document/d/1YA9y9HdO864X91h-ferVZw660yvMdzKWBjq7UJwy0ro/edit#heading=h.75ucj8dwghn4)
* https://github.com/2DegreesInvesting/tilt.explorative.analysis/

## Database insights

Insights about the tilt database without and with tilt indicators.

### Without indicators

Priority: Higher

- [ ] [Amount of companies (total, sector and sub-sector split, country-split)](https://github.com/2DegreesInvesting/tilt.explorative.analysis/tree/main#112-amount-of-companies-total-sector-and-sub-sector-split-country)
- [ ] [Amount of companies according to main activity of the companies](https://github.com/2DegreesInvesting/tilt.explorative.analysis/tree/main#113-main-activity-of-the-company)
- [ ] [Amount of companies according to employees of the companies](https://github.com/2DegreesInvesting/tilt.explorative.analysis/tree/main#113-main-activity-of-the-company)

Priority: Lower

- [ ] Map with companies
- [ ] Representativeness of database
- [ ] FIXME move. Table: Summary statistics

### With indicators

Priority: Undefined

- [ ] Clarify the input data for the plots, especially with regard to this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/474#event-9949409617). 
- [x] Emissions profile without financial data
- [ ] Sector profile without financial data
- [ ] Map with companies and climate indicators
- [ ] FIXME move. Table: Summary statistics

1.3 Interactivity

Priority: Lower

- [ ] FIXME move. Make the exploratory plots/tables interactive

## Financial insights

Plots and tables for insights about bank's data after matching it to tilt data.

Priority: Undefined

- [ ] Clarify the input data for the plots, especially with regard to this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/474#event-9949409617).
- [x] Sankey Plot with financial data
- [x] Emissions profile with financial data
- [ ] Emissions profile maps with financial data
- [ ] Sector profile with financial data
- [ ] Sector profile maps with financial data
- [ ] Sector profile plots/maps/other?

Priority: Lower

- [ ] Box plot
- [ ] Time series

Priority: Lower

- [ ] Summary statistic tables

## General

Priority: Undefined

- [ ] Customize colour schemes according to the new tilt design

**Comment by maurolepore** [comment]
Closing in favor or https://github.com/2DegreesInvesting/tiltPlot/milestone/1
